// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qttrfcaxzdsmrpslvuvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0dHJmY2F4emRzbXJwc2x2dXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzQ5NTMsImV4cCI6MjA2NzExMDk1M30.Ar9GE3B0zO0gZ6U1D2V8qSBQzKRgd9AsvNwFs1sIYUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});